/*
 * Principal.java
 *
 * Created on 19 de septiembre de 2008, 20:36
 */

package com.micropakito.server.formularios;

import com.micropakito.server.ServerHilo;
import com.micropakito.server.utilidades.Constantes;
import java.util.ArrayList;

/**
 *
 * @author  Administrador
 */
public class Principal extends javax.swing.JFrame {
    private static final int numeroServidores = 5;
    private static final int puertoInicio = Constantes.puertoInicio ;

    private ArrayList servidores = new ArrayList();
   
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        //inicio los servidores a nulo, ya que luego los añadiré por id
        //pero de forma desordenada. Para que estén todos inicializados
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnArrancar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuArrancarTodos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuPararTodos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        txtInfo.setColumns(20);
        txtInfo.setEditable(false);
        txtInfo.setFont(new java.awt.Font("Courier New", 0, 11));
        txtInfo.setLineWrap(true);
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        btnArrancar.setText("Arrancar");
        btnArrancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnArrancarMousePressed(evt);
            }
        });
        btnArrancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrancarActionPerformed(evt);
            }
        });

        btnParar.setText("Parar");
        btnParar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPararMousePressed(evt);
            }
        });

        jMenu1.setText("Servidor");

        jMenu3.setText("Arrancar");

        mnuArrancarTodos.setText("Todos");
        mnuArrancarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuArrancarTodosMousePressed(evt);
            }
        });
        jMenu3.add(mnuArrancarTodos);

        jMenuItem2.setText("Servidor 1");
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenu4.setText("Para");

        mnuPararTodos.setText("Todos");
        jMenu4.add(mnuPararTodos);

        jMenuItem4.setText("Servidor 1");
        jMenu4.add(jMenuItem4);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuración");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 422, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnParar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnArrancar))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnArrancar)
                        .add(16, 16, 16)
                        .add(btnParar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 249, Short.MAX_VALUE)
                        .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrancarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnArrancarActionPerformed

    private void btnArrancarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrancarMousePressed
        // TODO add your handling code here:
        ArrancarTodos();
    }//GEN-LAST:event_btnArrancarMousePressed

    private void mnuArrancarTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuArrancarTodosMousePressed
        // TODO add your handling code here:
        ArrancarTodos();
    }//GEN-LAST:event_mnuArrancarTodosMousePressed

    private void btnPararMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPararMousePressed
        // TODO add your handling code here:
        //PararTodos();
    }//GEN-LAST:event_btnPararMousePressed
    private void ArrancarTodos(){
    
         //s = new Servidor();
         for (int i = puertoInicio ;i < puertoInicio + numeroServidores ; i ++ ){
            //s.nuevoServidor( i , getTxtInfo(), servidores, this);
            this.getServidores().add( i - puertoInicio , new ServerHilo ( i , this.getServidores() ));

         }   
    }
//    private void PararTodos() {
//
//        s.pararServidores();
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public ArrayList getServidores() {
        return servidores;
    }

    public void setServidores(ArrayList servidores) {
        this.servidores = servidores;
    }
    public void pararServidores () {
//        Iterator it = this.getServidores().iterator();
//        while ( it.hasNext() ) {
//            ServerHilo sh = (ServerHilo)it.next();
//            sh.Parar();
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrancar;
    private javax.swing.JButton btnParar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuArrancarTodos;
    private javax.swing.JMenuItem mnuPararTodos;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtInfo
     */
    public javax.swing.JTextArea getTxtInfo() {
        return txtInfo;
    }

    /**
     * @param txtInfo the txtInfo to set
     */
    public void setTxtInfo(javax.swing.JTextArea txtInfo) {
        this.txtInfo = txtInfo;
    }
    
}
